### ISSUE TITLE
Chapter 2. International System of Units 2019 Revision

### ISSUE THREAD

**Issue by drfperez** [mit-teal/801#8]
I suggest to modify chapter 2 taking into account the latest revision of the International System of Units.
The revised definition of the kilogram is chosen to fix the numerical value of the Planck constant h, that of the ampere to fix the numerical value of the elementary charge e, that of the kelvin to fix the numerical value of the Boltzmann constant k (kB), and that of the mole to fix the numerical value of the Avogadro constant NA (L), all these numerical values being expressed in terms of the corresponding SI unit. The definitions of the remaining three base units, the second, the metre, and the candela fix the numerical value of the caesium hyperfine splitting ΔνCs, the speed of light in vacuum c, and the luminous intensity of the specified source Iv, just as they do at present.
https://iupac.org/100/stories/the-new-si
https://www.bipm.org/en/publications/si-brochure/
Regards from Barcelona,

Prof. Dr. Francisco Perez

**Comment by aamacdon** [comment]
Hi Prof. Perez, thank you very much for your suggestions! Dr. Dourmashkin made revisions to Chapter 2, and I believe the [updated version](https://github.com/mit-teal/801/blob/master/textbook/chapter02.pdf) addresses these points and the latest revisions of SI. Sorry for replying so late. Hope you are safe and well in Barcelona!
